### PR TITLE
Fix bug in deferred death and movement queues

### LINKED ISSUE #44: Peeps::queueForDeath() queues already dead Indiv-s in RadioactiveChallenge
Symptom:
Some individuals are queued for death even after they marked as dead already when RadioActiveWalls mode is on. This results indirectly allowing for individuals to be added to move queue even if they have no movement scheduled.
As a result ```getPopulationDensityAlongAxis``` will assert with ```assert(dir != Compass::CENTER);```

Expected:
No assert and dead individuals never should be queued twice.

This is my first ever github community contribution, so I am not familiar with the procedure. I am happy to create a PR with the fix, if you think it needs to be fixed. Please leave a comment and I get the work done.

### PR DESCRIPTION
**Pull request by davidrmiller**
This fixes #44 by preventing the radioactive challenge from placing an already-dead agent on the death queue, and preventing the movement of a dead agent while draining the movement queue.

### CODE REVIEW

File: src/endOfSimStep.cpp [hunk 1]
```diff
@@ -32,11 +32,13 @@ void endOfSimStep(unsigned simStep, unsigned generation)
 
         for (uint16_t index = 1; index <= p.population; ++index) { // index 0 is reserved
             Indiv &indiv = peeps[index];
-            int16_t distanceFromRadioactiveWall = std::abs(indiv.loc.x - radioactiveX);
-            if (distanceFromRadioactiveWall < p.sizeX / 2) {
-                float chanceOfDeath = 1.0 / distanceFromRadioactiveWall;
-                if (randomUint() / (float)RANDOM_UINT_MAX < chanceOfDeath) {
-                    peeps.queueForDeath(indiv);
+            if (indiv.alive) {
```
Comment (artofimagination) [inline src/endOfSimStep.cpp:35]: Is the check outside ```queueForDeath``` to optimize speedwise? Having the check inside the function is generally safer when it comes to reusability, although I saw you have an assert there to make sure it is not overlooked.

File: src/executeActions.cpp [hunk 2]
```diff
@@ -134,10 +134,8 @@ void executeActions(Indiv &indiv, std::array<float, Action::NUM_ACTIONS> &action
             Coord otherLoc = indiv.loc + indiv.lastMoveDir;
             if (grid.isInBounds(otherLoc) && grid.isOccupiedAt(otherLoc)) {
                 Indiv &indiv2 = peeps.getIndiv(otherLoc);
-                if (indiv2.alive) {
```
Comment (artofimagination) [inline src/executeActions.cpp:137]: Won't this result in assert in ```queueForDeath```?

File: src/endOfSimStep.cpp (hunk 1 above)
Comment (davidrmiller) [reply src/endOfSimStep.cpp:35]: Thanks for looking this over. Yes, it's just to optimize speed of the release version. The debug version is full of asserts to make sure callers are observing protocol so that the release version can be as small and fast as possible. It's a general style in this project, although a profiler would probably detect very little difference in this particular case.

File: src/executeActions.cpp (hunk 2 above)
Comment (davidrmiller) [reply src/executeActions.cpp:137]: I believe that indiv2.alive is always true here because it's the agent occupying the location at otherLoc, and only living agents can occupy locations.
